cache:
  directories:
  - $HOME/.m2
sudo: false
language:
    - java
jdk:
    - oraclejdk8
git:
  depth: 99999
addons:
  apt:
    packages:
      - oracle-java8-installer
install: 
    true
script:
    mvn install
